name: AHS.SaaS Core Pipeline
run-name: CI Build - ${{ github.event.head_commit.message }} by @${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.100-preview.1.25077.10"
          include-prerelease: true

      - name: Install Native AOT prerequisites
        run: sudo apt-get update && sudo apt-get install -y clang zlib1g-dev

      - name: Install Native AOT Workload
        run: dotnet workload install microsoft-net-sdk-aot
        env:
          DOTNET_INSTALL_KEEP_TEMPORARY_FILES: true

      - name: Restore dependencies
        run: dotnet restore AHS.SaaS.slnx -r linux-x64
        env:
          DOTNET_INSTALL_KEEP_TEMPORARY_FILES: true

      - name: Build
        run: dotnet build AHS.SaaS.slnx -c Release --no-restore

      - name: Test
        run: dotnet test --no-build -c Release --verbosity normal

      - name: Native AOT Publish Check (Gateway API)
        run: dotnet publish src/Presentation/AHS.Gateway.API/AHS.Gateway.API.csproj -c Release -r linux-x64 --no-restore
